DJstore/DJstore/urls.py

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('accounts/', include('accounts.urls')),
]

DJstore/accounts/urls.py
from django.urls import path
from . import views as v

app_name = 'accounts'
urlpatterns = [
    path('accounts/',v.register,name='register'),
    path('login',v.loginpage,name='login'),
    path('logout',v.logoutpage,name='logout')
]

DJstore/base/urls.py
from django.urls import path
from . import views as v

app_name = 'base'
urlpatterns = [
    path('',v.index,name='index'),
    path('add',v.add,name='add'),
    path('itpage/<str:pk>/',v.itpage,name='itpage'),
    path('buy/<str:pk>/',v.buy,name='buy'),
    path('myorder/',v.myorders,name='order'),
    path('mycart/',v.mycart,name='cart'),
    path('addcart/<str:pk>/',v.addcart,name='addcart')
]

DJstore/accounts/models.py
from django.db import models

# Create your models here.

DJstore/base/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    category = models.CharField(max_length=20)
    
    def __str__(self):
        return self.category

class Items(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=20)
    price = models.IntegerField(null=True)  
    description = models.TextField(max_length=200, null=True) 
    def __str__(self):
        return self.name

class PayMethods(models.Model):
    type = models.CharField(max_length=200)
    
    def __str__(self):
        return self.type

class Orders(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    item = models.ForeignKey(Items, on_delete=models.CASCADE, null=True)
    location = models.TextField(max_length=200, null=True)
    method = models.ForeignKey(PayMethods, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user.username} - Order"

class Mycart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    item = models.ForeignKey(Items, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - cart"

DJstore/accounts/views.py
from django.shortcuts import render,redirect
from base.models import Items,Category
from django.contrib.auth.models import User,auth
# Create your views here.
def register(request):
    if request.method == "POST":
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']


        if not all([username, firstname, lastname, password1, password2, email]):
            error = "All fields are required."
            return render(request, 'accounts/register.html', {'error': error})
        

        if password1 != password2:
            context = {'error': "you entered passwordes are not same "}
            return render(request,'accounts/register.html',context)
        

        if User.objects.filter(username=username).exists():
            context = {'error': "username already exists"}
            return render(request,'accounts/register.html',context)
        

        if User.objects.filter(email=email).exists():
            context = {'error': "Email already exists"}
            return render(request,'accounts/register.html',context)
        
        user = User.objects.create_user(username=username,password=password1,email=email,first_name=firstname,last_name=lastname)
        user.save();
        message = {'massage':"Successfully registered"}
        return render(request,'accounts:login',message)

    else:    
        return render(request,'accounts/register.html')


def loginpage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('base:index')
        else:
            message = {'message':"invalid cridentials"}
            return render(request,'accounts/loginpage.html',message)
    else:
        context={}
        return render(request,'accounts/loginpage.html',context)


def logoutpage(request):
    auth.logout(request)
    return redirect('base:index')

DJstore/base/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Items,Category,Orders,PayMethods,Mycart
from django.contrib.auth.decorators import login_required
from .form import ItemForm,OrderForm
from django.contrib import messages
from django.contrib.auth.models import User,auth
# Create your views here.
def index(request):
    items = Items.objects.all()
    context = {'items': items}
    return render(request,'base/index.html',context)
@login_required(login_url='accounts:login')
def add(request):
    form = ItemForm()
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            added= form.save(commit=False)
            added.owner = request.user
            added.save()
            return redirect('base:index')
        
    context = {'form':form}
    return render(request,'base/add.html',context)
def itpage(request,pk):
    item = get_object_or_404(Items, pk=pk)
    context ={'item':item}
    return render(request,'base/itpage.html',context)

@login_required(login_url='accounts:login')
def buy(request,pk):
    item = Items.objects.get(pk=pk)
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.item = item
            order.user =request.user
            order.save()
            return redirect('base:index')
        else:
            context ={'item':item , 'form':form}
            return render(request,'base/buy.html',context)
    else:
        context ={'item':item , 'form':form}
        return render(request,'base/buy.html',context)

@login_required(login_url='accounts:login')
def myorders(request):
    myorder = Orders.objects.filter(user=request.user)
    context = {'myorder' : myorder}
    return render(request,'base/orders.html',context)

@login_required(login_url='accounts:login')
def mycart(request):

    mycart = Mycart.objects.filter(user=request.user)
    context = {'mycart' : mycart}
    return render(request,'base/cart.html',context)

@login_required(login_url='accounts:login')
def addcart(request,pk):
    item = get_object_or_404(Items, pk=pk)

    if Mycart.objects.filter(user=request.user,item=item).exists():
        return redirect('base:cart')
    cart = Mycart.objects.create(user = request.user,item=item)
    cart.save()
    return redirect('base:cart')

DJstore/accounts/templates/accounts/loginpage.html
{% extends 'main.html' %}

{% block body%}

{% if message %}
<h2> {{ message}} </h2>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <label for="username">username</label>
    <input type="text" id="username" name="username">
    <br>
    <br>
    <label for="password">password</label>
    <input type="password" id="password" name="password">
    <input type="submit" value="Login">
</form>
<h3>Not have a account ? <a href="{% url 'accounts:register' %}">Register</a></h3>
{% endblock %}

DJstore/accounts/templates/accounts/register.html
{% extends 'main.html' %}

{% block body%}
<h1>Register page</h1>

{% if error %}
<h2>{{ error }} </h2>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <label for="username">username</label>
    <input type="text" id="username" name="username">
    <br>
    <br>
    <label for="firstname">First name</label>
    <input type="text" id="firstname" name="firstname">
    <br>
    <br>
    <label for="lastname">last name</label>
    <input type="text" id="lastname" name="lastname">
    <br>
    <br>
    <label for="password1">password</label>
    <input type="password" id="password1" name="password1">
    <br><br>
    <label for="password2">verify password</label>
    <input type="password" id="password2" name="password2">
    <br><br>
    <label for="email">Email</label> 
    <input type="email" id='email' name="email">

    <input type="submit" value="Register">
</form>
{% endblock %}

DJstore/base/templates/base/Buy.html
{% extends 'main.html' %}

{% block body%}

<h1>{{item.name}} </h1>

<h2>price = {{item.price}}</h2>

<form action="" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Buy">
</form>
{% endblock %}

DJstore/base/templates/base/add.html
{% extends 'main.html' %}

{% block body%}
<h1>Add Item </h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock %}

DJstore/base/templates/base/cart.html
{% extends 'main.html' %}

{% block body%}


{% for cart in mycart %}
<div>
    <h1> Item = {{cart.item}} </h1>

    <h2>price:- {{cart.item.price}}</h2>
    <h3></h3>
    <a href="{% url 'base:buy' cart.item.id %}"">Buy Now</a>
</div>
{% endfor %}

{% endblock %}

DJstore/base/templates/base/index.html
{% extends 'main.html' %}

{% block body %}


    <h1>Available items :- </h1>
<div style="text-align: center;">
    {% for item in items %}

        
        <a href="{% url 'base:itpage' item.id %}">
            <div class="items" >
                <h2>  Name:- {{ item.name}}</h2>
                <h3>    Price:- {{ item.price}}</h3> 
                <h4>    owner:- {{ item.owner }} </h4>
            </div>
        </a>
    {% endfor %}
</div>

{% endblock %}

DJstore/base/templates/base/itpage.html
{% extends 'main.html' %}

{% block body %}

{% if message %}
<h1>{{ message}}</h1>
{% endif %}

<h1>{{item.name}}</h1>
<p>{{item.description}}</p>
<h3>price :- {{item.price}} </h3>
<h4>{{item.owner}}</h4>
<a href="{% url 'base:buy' item.id %}">Buy Now</a>
<a href="{% url 'base:addcart' item.id %}">Add to cart</a>
{% endblock %}

DJstore/base/templates/base/orders.html
{% extends 'main.html' %}

{% block body%}

{% for order in myorder %}
<div>
    <h1> Item = {{order.item}} </h1>    

    <h2>Address = {{order.location}}</h2>
</div>
{% endfor %}

{% endblock %}

DJstore/templates/main.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'base/main.css' %}">
    <title>DJ store</title>
</head>
<body>
    {% include 'nav.html'%}
    
    {% block body%}
    {% endblock%}

</body>
</html>

DJstore/templates/nav.html
<nav class="navbar">
    <ul>
        <li><h3><a href="{% url 'base:index' %}">Home</a></h3></li>
        <li><h3><a href="{% url 'base:add' %}">Add items</a></h3> </li>
        <li><h3><a href="{% url 'base:cart' %}">My cart</a></h3></li>
        <li><h3><a href="{% url 'base:order' %}">My orders</a></h3></li>
        {% if user.is_authenticated %}
        <li><h3><a href="{% url 'accounts:logout' %}">Logout</a></h3></li>
        {% else %}
        <li><h3><a href="{% url 'accounts:login' %}">Login</a></h3></li>
        {% endif %}
    </ul>   
    <br>
</nav>